# Generated by Django 3.1.2 on 2020-10-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '커뮤니티 사용자', 'verbose_name_plural': '커뮤니티 사용자'},
        ),
        migrations.AddField(
            model_name='user',
            name='usermail',
            field=models.EmailField(default='Null@Null.Null', max_length=128, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
